- domain_lora_scale: 1.0
  adapter_lora_path: models/Motion_Module/v3_sd15_adapter.ckpt
  dreambooth_path: ''
  inference_config: configs/inference/inference-v3.yaml
  motion_module: models/Motion_Module/v3_sd15_mm.ckpt
  controlnet_config: configs/inference/sparsectrl/latent_condition.yaml
  controlnet_path: models/SparseCtrl/v3_sd15_sparsectrl_rgb.ckpt
  H: 256
  W: 384
  seed:
  - 123
  - 234
  steps: 25
  guidance_scale: 8.5
  controlnet_image_indexs:
  - 0
  controlnet_images:
  - __assets__/demos/image/painting.png
  prompt:
  - an oil painting of a sailboat in the ocean wave
  - an oil painting of a sailboat in the ocean wave
  n_prompt:
  - worst quality, low quality, letterboxed
  L: 16
  random_seed:
  - 123
  - 234
